x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  image: linyq1/narratoai:latest
  volumes:
    - ./:/NarratoAI
  environment:
    - VPN_PROXY_URL=http://host.docker.internal:7890
  restart: always

services:
  webui:
    <<: *common
    container_name: webui
    ports:
      - "8501:8501"
    command: ["webui"]
